services:
  ocr_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr_api_chinh_vd
    volumes:
      - .:/app
    ports:
      - "8000:8000"  
    environment:
      - PYTHONUNBUFFERED=1
